### ISSUE TITLE
 A process in the process pool was terminated abruptly while the future was running or pending

### ISSUE THREAD

**Issue by lizhen2017** [NVIDIA-Merlin/HugeCTR#191]
As the title, I run the script: python ../tools/embedding_plugin/performance_profile/preprocess.py --src_csv_path=train.txt --dst_csv_path=train.out.txt --normalize_dense=0 --feature_cross=0 in the official docker，but it core dumped with  A process in the process pool was terminated abruptly while the future was running or pending

```
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 295, in _queue_management_worker
    shutdown_worker()
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 253, in shutdown_worker
    call_queue.put_nowait(None)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 129, in put_nowait
    return self.put(obj, False)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 83, in put
    raise Full
queue.Full

Traceback (most recent call last):
  File "../tools/embedding_plugin/performance_profile/preprocess.py", line 256, in <module>
    preprocess(src_csv_path, dst_csv_path, normalize_dense, feature_cross)
  File "../tools/embedding_plugin/performance_profile/preprocess.py", line 221, in preprocess
    ret = future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending
```

**Comment by Jianbing-D** [comment]
@lizhen2017 Could you please provide the full error log, and you hardware configuration so that we can try to reproduce this issue. Thanks.

**Comment by Jianbing-D** [comment]
@lizhen2017 And what is the docker tag you used?

**Comment by viswa-nvidia** [comment]
@minseokl , do we need to track this ?
