### ISSUE TITLE
[BUG] HugeCTR datacollector illegal memory access when scale from 4 gpu to 8 gpu

### ISSUE THREAD

**Issue by mengdong** [NVIDIA-Merlin/HugeCTR#250]
**Describe the bug**
HugeCTR datacollector illegal memory access when scale from 4 gpu to 8 gpu

**To Reproduce**
Follow: https://github.com/mengdong/merlin-on-vertex/blob/main/src/training/hugectr/HUGHCTR_CRASH.md

**Expected behavior**
8 gpu should run without illegal memory access 

**Screenshots**
09-10-21 04:53:44 - Starting model fitting
=====================================================Model Fit=====================================================
[90d40h53m44s][HUGECTR][INFO]: Use non-epoch mode with number of iterations: 5000
[90d40h53m44s][HUGECTR][INFO]: Training batchsize: 8192, evaluation batchsize: 8192
[90d40h53m44s][HUGECTR][INFO]: Evaluation interval: 500, snapshot interval: 0
[90d40h53m44s][HUGECTR][INFO]: Sparse embedding trainable: 1, dense network trainable: 1
[90d40h53m44s][HUGECTR][INFO]: Use mixed precision: 0, scaler: 1.000000, use cuda graph: 1
[90d40h53m44s][HUGECTR][INFO]: lr: 0.001000, warmup_steps: 1, decay_start: 0, decay_steps: 1, decay_power: 2.000000, end_lr: 0.000000
[90d40h53m44s][HUGECTR][INFO]: Training source file: /criteo_data/criteo_processed_parquet/train/_file_list.txt
[90d40h53m44s][HUGECTR][INFO]: Evaluation source file: /criteo_data/criteo_processed_parquet/valid/_file_list.txt
[HCDEBUG][ERROR] Runtime error: an illegal memory access was encountered /var/tmp/HugeCTR/HugeCTR/include/data_readers/data_collector.hpp:236

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/src/trainer/task.py", line 254, in <module>
    main(args)
  File "/src/trainer/task.py", line 114, in main
    model.fit(num_epochs=args.num_epochs,
RuntimeError: [HCDEBUG][ERROR] Runtime error: an illegal memory access was encountered /var/tmp/HugeCTR/HugeCTR/include/data_readers/data_collector.hpp:236

[HCDEBUG][ERROR] Runtime error: an illegal memory access was encountered /var/tmp/HugeCTR/HugeCTR/pybind/model.cpp:406

terminate called after throwing an instance of 'HugeCTR::internal_runtime_error'
  what():  [HCDEBUG][ERROR] Runtime error: an illegal memory access was encountered /var/tmp/HugeCTR/HugeCTR/src/metrics.cu:497

[ec0eeea8e953:00309] *** Process received signal ***
[ec0eeea8e953:00309] Signal: Aborted (6)
[ec0eeea8e953:00309] Signal code:  (-6)
[ec0eeea8e953:00309] [ 0] /usr/lib/x86_64-linux-gnu/libc.so.6(+0x46210)[0x7f10e79ef210]
[ec0eeea8e953:00309] [ 1] /usr/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f10e79ef18b]
[ec0eeea8e953:00309] [ 2] /usr/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f10e79ce859]
[ec0eeea8e953:00309] [ 3] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x9e911)[0x7f10cd823911]
[ec0eeea8e953:00309] [ 4] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xaa38c)[0x7f10cd82f38c]
[ec0eeea8e953:00309] [ 5] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xa9369)[0x7f10cd82e369]
[ec0eeea8e953:00309] [ 6] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(__gxx_personality_v0+0x2a1)[0x7f10cd82ed21]
[ec0eeea8e953:00309] [ 7] /usr/lib/x86_64-linux-gnu/libgcc_s.so.1(+0x10bef)[0x7f10cd738bef]
[ec0eeea8e953:00309] [ 8] /usr/lib/x86_64-linux-gnu/libgcc_s.so.1(_Unwind_RaiseException+0x331)[0x7f10cd739281]
[ec0eeea8e953:00309] [ 9] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(__cxa_throw+0x3c)[0x7f10cd82f69c]
[ec0eeea8e953:00309] [10] /usr/local/hugectr/lib/libhuge_ctr_shared.so(+0x20bf9a)[0x7f10e46e7f9a]
[ec0eeea8e953:00309] [11] /usr/local/hugectr/lib/libhuge_ctr_shared.so(_ZN7HugeCTR7metrics3AUCIfED1Ev+0x86)[0x7f10e4ca2cd6]
[ec0eeea8e953:00309] [12] /usr/local/hugectr/lib/libhuge_ctr_shared.so(_ZN7HugeCTR7metrics3AUCIfED0Ev+0xd)[0x7f10e4ca2dcd]
[ec0eeea8e953:00309] [13] /usr/local/hugectr/lib/libhuge_ctr_shared.so(_ZN7HugeCTR5ModelD1Ev+0x127)[0x7f10e4e2c327]
[ec0eeea8e953:00309] [14] /usr/local/hugectr/lib/hugectr.so(+0x4b956)[0x7f10e71a5956]
[ec0eeea8e953:00309] [15] /usr/local/hugectr/lib/hugectr.so(_ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE10_M_releaseEv+0x48)[0x7f10e71bb528]
[ec0eeea8e953:00309] [16] /usr/local/hugectr/lib/hugectr.so(+0x61f34)[0x7f10e71bbf34]

**Environment (please complete the following information):**
GCP A100 a2-high-8g, | NVIDIA-SMI 470.57.02 Driver Version: 470.57.02 CUDA Version: 11.4
nvcr.io/nvidia/merlin/merlin-training:21.09

**Comment by shijieliu** [comment]
Fixed in commit https://github.com/NVIDIA-Merlin/HugeCTR/commit/6dcbc1231fae46f31962602a030d38beb9e379d2 . Thanks!

**Comment by mengdong** [comment]
update: @sohn21c actively working with hugeCTR team to verify
