### ISSUE TITLE
[Question] How to have multiple inference sessions in a multi-GPU instance?

### ISSUE THREAD

**Issue by shoyasaxa** [NVIDIA-Merlin/HugeCTR#276]
Hello, 

I see that the an inference session only uses 1 GPU, since we have to use a `gpu_id` parameter in `InferenceParams` object. I was wondering if it is possible to use multiple GPUs for one inference session, or use multiple GPUs and multiple inference sessions to speed up inference. 

I have so far tried to use the `multiprocessing` Python library to use 4 inference sessions across 4 GPUs, but have been unsuccessful. 

I have tried roughly the following:
```
gpu_ids = [0,1,2,3]
inference_sessions = [] 
for gpu_id in gpu_ids:
    inference_params = InferenceParams(
        model_name = "dlrm",
        max_batchsize = batch_size,
        hit_rate_threshold = 0.6,
                            # path to where you save the dense model
        dense_model_file = "/path/to/my/_dense_.model",
        sparse_model_files = [".path/to/my/0_sparse.model"],
        device_id = gpu_id,
        use_gpu_embedding_cache = True,
        cache_size_percentage = 0.2,
        i64_input_key = True
    )

    inference_session = CreateInferenceSession(
        "model_config.json", 
        inference_params
    )
    
    inference_sessions.append(inference_session)

def inference_thread(inference_session):
        preds = inference_session.predict(
            num_batches=total_batch_size,
            source="/path/to/my/_file_list.txt",
            data_reader_type=hugectr.DataReaderType_t.Parquet,
            check_type=hugectr.Check_t.Non,
            slot_size_array=my_slot_size_array
        )

from multiprocessing import Process
for i in gpu_ids:
   p = Process(target=inference_thread, args=(inference_sessions[i])
   p.start()

```
This above errors with 

```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/ipykernel_616/41973579.py", line 51, in inference_thread
    preds = inference_session.predict(
RuntimeError: Runtime error: initialization error /var/tmp/HugeCTR/HugeCTR/include/utils.hpp:220 
```
In fact, it fails even if I only have 1 GPU and 1 process as well.

I have also tried to initialize the inference session in the separate process like 
```
def inference_thread(gpu_id):
    inference_params = InferenceParams(
        model_name = "dlrm",
        max_batchsize = batch_size,
        hit_rate_threshold = 0.6,
                            # path to where you save the dense model
        dense_model_file = "/path/to/my/_dense_.model",
        sparse_model_files = ["/path/to/my/0_sparse.model"],
        device_id = gpu_id,
        use_gpu_embedding_cache = True,
        cache_size_percentage = 0.2,
        i64_input_key = True
    )

    inference_session = CreateInferenceSession(
        "model_config.json", 
        inference_params
    )
    
    inference_sessions[0].predict(
        num_batches=2,
        source="/path/to/my/_file_list.txt",
        data_reader_type=hugectr.DataReaderType_t.Parquet,
        check_type=hugectr.Check_t.Non,
        slot_size_array=my_slot_size_array
    )

p = Process(target=inference_thread, args=(0))
p.start()
p.join()
```
but this fails with 
```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/ipykernel_818/2868833798.py", line 23, in inference_thread
    inference_session = CreateInferenceSession(
RuntimeError: Runtime error: the operation cannot be performed in the present state /var/tmp/HugeCTR/HugeCTR/include/utils.hpp:220 
```

Could you please provide guidance on how we could achieve multiple inference sessions running on a multiple GPU instance? Thank you so much!

I am using a docker image built from `merlin-training:21.11` by the way.

**Comment by shoyasaxa** [comment]
I have managed to get it working with the second method of declaring the inference session in each process and also moving these imports to within the `inference_thread` function. 
```
from hugectr.inference import InferenceParams, CreateInferenceSession
from mpi4py import MPI
import hugectr
```

However, this is only when done in a Jupyter Notebook - when I try to run the code in a K8 job, it still fails with 

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/oraclecore/oraclecore/cars/prediction/predictor_multi_gpu.py", line 57, in inference_thread
    inference_session = CreateInferenceSession(
RuntimeError: Runtime error: the operation cannot be performed in the present state /var/tmp/HugeCTR/HugeCTR/include/utils.hpp:220 
```

At first, I noticed that if I import `pytorch` in the notebook, I also got this above error. So I took out the pytorch import in the job as well, but the same error persists. Could you please shed more light on what the `present state` is in the error message? Thank you!

**Comment by yingcanw** [comment]
@shoyasaxa Thanks for your feedback. Since the python interface provided here is only used for the functional verification of the inference results, the scenario you mentioned about deploy the single model on multi-GPU with  multi-session (model instance), we have been supported it in the  [HugeCTR Backend ](https://github.com/triton-inference-server/hugectr_backend/blob/main/docs/architecture.md#hugectr-backend-framework), which also supports more complex scenarios, like multi-models deployed on multi-gpus with multi-instance.
You can refer to the [samples ](https://github.com/triton-inference-server/hugectr_backend/tree/main/samples) here for multi-session deployment case.
