### ISSUE TITLE
[BUG] Cannot use TFEmbedding in tf.distribute.MultiWorkerMirroredStrategy()

### ISSUE THREAD

**Issue by tonyf** [NVIDIA-Merlin/HugeCTR#315]
I'm trying to train a Keras model with the sok TFEmbedding layer as a drop in replacement for `tf.keras.layers.Embedding`. However, when calling `model.fit` or when using a custom training loop as in the examples, the following exception is raised.

```
RuntimeError: The forward propagation of TFDistributedEmbedding cannot be called in cross_replica_context.
```

Here's the training code (model.fit version).
```
class MatrixFactorization(tf.keras.Model):
    def __init__(
        self,
        user_ids: list[int],
        embedding_size: int = 32,
        batch_size: int = 128,
    ) -> None:
        super().__init__()
        self.model = tf.keras.Sequential(
            [
                tf.keras.layers.Input(shape=(1), batch_size=batch_size),
                tf.keras.layers.IntegerLookup(vocabulary=user_ids),
                TFDistributedEmbedding(
                    vocabulary_size=len(user_ids) + 1,
                    embedding_vec_size=embedding_size,
                    comm_options=tf.distribute.experimental.CommunicationOptions(
                        bytes_per_pack=0,
                        timeout_seconds=None,
                        implementation=tf.distribute.experimental.CommunicationImplementation.NCCL,
                    ),
                ),
            ]
        )
        self.task = tfrs.tasks.Retrieval(
            metrics=tfrs.metrics.FactorizedTopK(
                tf.data.Dataset.from_tensor_slices(user_ids)
                .batch(batch_size)
                .map(self.model)
            )
        )

    def call(
        self, features: dict[str, tf.Tensor], training: bool = False
    ) -> dict[str, tf.Tensor]:
        user_embeddings = self.model(features["user_id"])
        friend_embeddings = self.model(features["friend_id"])
        return tf.keras.layers.Dot(axes=1)([user_embeddings, friend_embeddings])


def get_dataset_sizes(table_name: str) -> tuple[int, int, int]:
    bq_client = bigquery.Client()
    dataset_size = bq_client.get_table(table_name).num_rows

    train_size = math.floor(dataset_size * 0.8)
    eval_size = math.floor(dataset_size * 0.1)
    validation_size = math.floor(dataset_size * 0.1)

    return train_size, eval_size, validation_size


def get_vocabulary(table_name: str) -> list[int]:
    bq_client = bigquery.Client()
    user_ids = set(
        bq_client.query(
            f"SELECT DISTINCT(user_profile_id) FROM {table_name};"
        ).to_dataframe()["user_profile_id"]
    )
    friend_ids = set(
        bq_client.query(
            f"SELECT DISTINCT(friend_user_profile_id) FROM {table_name};"
        ).to_dataframe()["friend_user_profile_id"]
    )
    return list(user_ids | friend_ids)


def get_dataset(
    table_name: str,
    gcp_project_id: str,
    batch_size: int,
    rank: int = 0,
    size: int = 1,
    offset: int = 0,
    limit: Optional[int] = None,
    seed: Optional[int] = None,
) -> tf.data.Dataset:
    from tensorflow_io.bigquery import BigQueryClient 

    tf_bq_client = BigQueryClient()

    table_spec = table_name.split(".")
    read_session = tf_bq_client.read_session(
        "projects/" + gcp_project_id,
        gcp_project_id,
        table_spec[1],
        table_spec[0],
        ["user_profile_id", "friend_user_profile_id"],
        [dtypes.int64, dtypes.int64],
        requested_streams=1,
    )

    dataset = (
        read_session.parallel_read_rows()
        .map(
            lambda x: {
                "user_id": x["user_profile_id"],
                "friend_id": x["friend_user_profile_id"],
            }
        )
        .shuffle(1000, seed=seed)
        .skip(offset)
    )
    if limit:
        dataset = dataset.take(limit)

    return (
        dataset.shard(size, rank)
        .prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
        .repeat()
        .batch(batch_size)
    )


def train_func(config: dict[str, Any]) -> dict[str, Any]:
    gpus = tf.config.list_physical_devices("GPU")
    tf.config.set_visible_devices(gpus, "GPU")
    strategy = tf.distribute.MultiWorkerMirroredStrategy()

    batch_size = int(config["batch_size"])
    num_workers = int(config["num_workers"])
    global_batch_size = batch_size * num_workers
    train_size, eval_size, validation_size = get_dataset_sizes(config["table"])
    user_ids = get_vocabulary(config["table"])

    with strategy.scope():
        model = MatrixFactorization(
            user_ids=user_ids,
            embedding_size=32,
            batch_size=batch_size,
        )
        model.compile(
            optimizer=tf.keras.optimizers.Adagrad(
                config["learning_rate"] * num_workers
            ),
            metrics=["accuracy"],
        )
        train_ds = strategy.experimental_distribute_dataset(
            get_dataset(
                config["table"],
                config["gcp_project_id"],
                batch_size=batch_size,
                limit=train_size,
            )
        )
        validation_ds = strategy.experimental_distribute_dataset(
            get_dataset(
                config["table"],
                config["gcp_project_id"],
                batch_size=batch_size,
                offset=train_size + eval_size,
            )
        )

    print("Training")
    model.fit(
        train_ds,
        steps_per_epoch=(train_size // batch_size),
        epochs=config.get("epochs"),
        validation_data=validation_ds,
        validation_steps=(validation_size // batch_size),
        callbacks=[],
    )


def main(args: argparse.Namespace) -> None:
    ray.init(address="auto", include_dashboard=True)
    print("Ray initialized, use gpu:", args.use_gpu)
    trainer = Trainer(
        backend="tensorflow",
        num_workers=args.num_workers,
        use_gpu=args.use_gpu,
        resources_per_worker={"GPU": 4.0 if args.use_gpu else 0.0},
    )
    trainer.start()
    results = trainer.run(train_func=train_func, config=vars(args))
    trainer.shutdown()
    print(f"Results: {results[0]}")

```

Full dump of logs
```
(BackendExecutor pid=659, ip=172.31.79.57) [INFO]: sparse_operation_kit is imported
(BaseWorkerMixin pid=720, ip=172.31.79.57) [INFO]: sparse_operation_kit is imported
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:51.803347: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:51.803749: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:51.804084: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:51.804413: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:51.812047: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:51.812402: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:51.812732: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:51.813057: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:51.813380: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:51.813711: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:51.814037: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:51.814399: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:51.816277: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
(BaseWorkerMixin pid=720, ip=172.31.79.57) To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:52.718781: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:52.719164: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:52.719500: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:52.719830: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:52.720174: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:52.720534: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:52.720874: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:52.721221: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:52.721563: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:52.721898: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:52.722278: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:52.722617: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.598552: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.598978: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.599344: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.599704: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.600042: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.600384: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.600717: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.601056: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.601391: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.601665: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.601716: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 14638 MB memory:  -> device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:00:1b.0, compute capability: 7.0
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.602333: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.602624: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.602655: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 14638 MB memory:  -> device: 1, name: Tesla V100-SXM2-16GB, pci bus id: 0000:00:1c.0, compute capability: 7.0
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.603096: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.603375: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.603406: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 14638 MB memory:  -> device: 2, name: Tesla V100-SXM2-16GB, pci bus id: 0000:00:1d.0, compute capability: 7.0
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.603857: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.604135: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.604164: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 14638 MB memory:  -> device: 3, name: Tesla V100-SXM2-16GB, pci bus id: 0000:00:1e.0, compute capability: 7.0
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.607454: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.607808: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.608136: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.608459: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.608800: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.609125: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.609444: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.609763: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.610083: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.610445: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.610778: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.611108: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.611545: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.611882: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.612212: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.612541: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.612873: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.613148: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:worker/replica:0/task:0/device:GPU:0 with 14638 MB memory:  -> device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:00:1b.0, compute capability: 7.0
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.613363: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.613645: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:worker/replica:0/task:0/device:GPU:1 with 14638 MB memory:  -> device: 1, name: Tesla V100-SXM2-16GB, pci bus id: 0000:00:1c.0, compute capability: 7.0
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.613876: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.614196: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:worker/replica:0/task:0/device:GPU:2 with 14638 MB memory:  -> device: 2, name: Tesla V100-SXM2-16GB, pci bus id: 0000:00:1d.0, compute capability: 7.0
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.614405: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.614686: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:worker/replica:0/task:0/device:GPU:3 with 14638 MB memory:  -> device: 3, name: Tesla V100-SXM2-16GB, pci bus id: 0000:00:1e.0, compute capability: 7.0
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.650961: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:272] Initialize GrpcChannelCache for job worker -> {0 -> 172.31.79.57:59461}
(BaseWorkerMixin pid=720, ip=172.31.79.57) 2022-05-16 21:17:54.651316: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:437] Started server with target: grpc://172.31.79.57:59461
(BaseWorkerMixin pid=720, ip=172.31.79.57) Factorizing 43957277 users
(BaseWorkerMixin pid=720, ip=172.31.79.57) Entering scope
(BaseWorkerMixin pid=720, ip=172.31.79.57) Initialize Model
Traceback (most recent call last):
  File "/home/ray/train.py", line 389, in <module>
    main(args)
  File "/home/ray/train.py", line 327, in main
    results = trainer.run(train_func=train_func, config=vars(args))
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/trainer.py", line 334, in run
    for intermediate_result in iterator:
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/trainer.py", line 719, in __next__
    self._final_results = self._run_with_error_handling(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/trainer.py", line 687, in _run_with_error_handling
    return func()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/trainer.py", line 791, in _finish_training
    return self._backend_executor.finish_training()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/utils.py", line 173, in <lambda>
    return lambda *args, **kwargs: ray.get(actor_method.remote(*args, **kwargs))
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/worker.py", line 1809, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::BackendExecutor.finish_training() (pid=659, ip=172.31.79.57, repr=<ray.train.backend.BackendExecutor object at 0x7f3fef8f20a0>)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/backend.py", line 544, in finish_training
    results = self.get_with_failure_handling(futures)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/backend.py", line 563, in get_with_failure_handling
    success, failed_worker_indexes = check_for_failure(remote_values)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/utils.py", line 53, in check_for_failure
    ray.get(object_ref)
ray.exceptions.RayTaskError(RuntimeError): ray::BaseWorkerMixin._BaseWorkerMixin__execute() (pid=720, ip=172.31.79.57, repr=<ray.train.worker_group.BaseWorkerMixin object at 0x7fbd40a02700>)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/worker_group.py", line 26, in __execute
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/backend.py", line 535, in end_training
    output = session.finish()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/session.py", line 117, in finish
    func_output = self.training_thread.join()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/utils.py", line 101, in join
    raise self.exc
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/utils.py", line 94, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/ray/train/utils.py", line 143, in <lambda>
    return lambda: train_func(config)
  File "/home/ray/train.py", line 227, in train_func
  File "/home/ray/train.py", line 90, in __init__
  File "/home/ray/anaconda3/lib/python3.9/site-packages/tensorflow/python/training/tracking/base.py", line 629, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/ray/anaconda3/lib/python3.9/site-packages/tensorflow/python/autograph/impl/api.py", line 692, in wrapper
    raise e.ag_error_metadata.to_exception(e)
RuntimeError: Exception encountered when calling layer "tf_distributed_embedding" (type TFDistributedEmbedding).

in user code:

    File "/home/ray/anaconda3/lib/python3.9/site-packages/merlin_sok-1.1.3-py3.9-linux-x86_64.egg/sparse_operation_kit/embeddings/tf_distributed_embedding.py", line 153, in call  *
        raise RuntimeError("The forward propagation of TFDistributedEmbedding "

    RuntimeError: The forward propagation of TFDistributedEmbedding cannot be called in cross_replica_context.


Call arguments received:
  • inputs=tf.Tensor(shape=(2500, 1), dtype=int64)
```

**Environment**
 - Graphic card: 4xNVIDIA V100
 - CUDA version: CUDA 11.2

**Comment by Jianbing-D** [comment]
> in user code:

    File "/home/ray/anaconda3/lib/python3.9/site-packages/merlin_sok-1.1.3-py3.9-linux-x86_64.egg/sparse_operation_kit/embeddings/tf_distributed_embedding.py", line 153, in call  *
        raise RuntimeError("The forward propagation of TFDistributedEmbedding "

    RuntimeError: The forward propagation of TFDistributedEmbedding cannot be called in cross_replica_context.

This error is throwed from [here](https://github.com/NVIDIA-Merlin/HugeCTR/blob/master/sparse_operation_kit/sparse_operation_kit/embeddings/tf_distributed_embedding.py#L152-L154).

It seems the `TFDistributedEmbedding.call(...)` is not invoked under `tf.distribute.ReplicaContext`. 

Could you please provide your custom training loop and how you started training processes?

**Comment by tonyf** [comment]
Is there a reason why `TFDistributedEmbedding.call(...)` cannot be called in a `cross_replica_context`? Isn't this always going to be the case in the training loop under `tf.distribute.MultiWorkerMirroredStrategy()`?

Need to dig around to find the custom training loop again. But, it was based off of the DLRM example code.

**Comment by Jianbing-D** [comment]
`TFDistributedEmbedding` will access the collective methods through `tf.distribute.ReplicaContext`. In other words, if `call(...)` is not called under `ReplicaContext`, then `tf.distribute.get_replica_context()` will return `None`, then there is no way to do collective communication because there is no available collective APIs.

**Comment by EvenOldridge** [comment]
@tonyf were you able to get it working?  Please reopen if there is still an issue.
