### ISSUE TITLE
[BUG] Failed to process day23 of criteo data.

### ISSUE THREAD

**Issue by zpcalan** [NVIDIA-Merlin/HugeCTR#386]
**Describe the bug**
Failed to process day23 of criteo data. But day0-22 is successfully processed.
Error info:
```
Warning: existing /root/HugeCTR/etc_data/day23 is erased
Preprocessing script: Pandas
Getting the first few examples from the uncompressed dataset...
Counting the number of samples in day_23 dataset...
The first 0 examples will be used in day_23 dataset.
Shuffling dataset...
Preprocessing...
2023-04-07 08:07:14,053 read a CSV file
2023-04-07 08:07:14,054 _fill_missing_features_and_split
2023-04-07 08:07:14,084 _merge_and_transform_series
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "criteo_script/preprocess.py", line 95, in _merge_and_transform_series
    min_max = (np.int64(result_series[col].min()), np.int64(result_series[col].max()))
ValueError: cannot convert float NaN to integer
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "criteo_script/preprocess.py", line 261, in <module>
    preprocess(src_csv_path, dst_csv_path, normalize_dense, feature_cross)
  File "criteo_script/preprocess.py", line 196, in preprocess
    for idx, ret in enumerate(future.result()):
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
ValueError: cannot convert float NaN to integer
MpiInitService: Initialized!
[HCTR][08:07:21.959][ERROR][RK0][main]: Cannot open argv[1]
[HCTR][08:07:21.960][INFO][RK0][main]: /root/HugeCTR/etc_data/day23/train exist
[HCTR][08:07:21.960][INFO][RK0][main]: /root/HugeCTR/etc_data/day23/train/sparse_embedding0.data
[HCTR][08:07:21.960][ERROR][RK0][main]: vec_string.size() != KEYS_WIDE_MODEL+KEYS_DENSE_MODEL+dense_dim+label_dim
[HCTR][08:07:21.960][ERROR][RK0][main]:
```

**To Reproduce**
1. Download day23.gz from https://ailab.criteo.com/download-criteo-1tb-click-logs-dataset/
2.`bash preprocess.sh 23 /root/HugeCTR/etc_data/day23 pandas 1 1`

**Expected behavior**
Day23's data is processed just like day0-22 data.

**Environment (please complete the following information):**
All of the commands above is launched inside the container using Tesla V100.

**Comment by JacoCheung** [comment]
Hi @zpcalan , I tried to reproduce but didn't encounter the issue, maybe can you re-download dataset and re-do the preprocessing?

**Comment by zpcalan** [comment]
OK, I'll try it later.

**Comment by zpcalan** [comment]
I retry and error disappeared. Closing this issue.
