### ISSUE TITLE
[Question] Failed to run lookup sparse distribute example

### ISSUE THREAD

**Issue by Nov11** [NVIDIA-Merlin/HugeCTR#391]
This is run in a merlin container.
The file is sparse_operation_kit/sparse_operation_kit/experiment/examples/lookup_sparse_distributed_example.py
Command: horovodrun -np 2 python lookup_sparse_distributed_example.py

It reports 'ncclGroupEnd failed: internal error '. 
What does this imply? Just cannot find a clue.
Possibly dependency on host machine is not compatible?

```
root@ccb862ae1c6d:/host_data1/repo/huge-ctr-3/sparse_operation_kit/sparse_operation_kit/experiment/examples# !19
horovodrun -np 2 python lookup_sparse_distributed_example.py
2023-04-17 12:18:26.485449: I tensorflow/core/platform/cpu_feature_guard.cc:194] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-17 12:18:26.651787: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[1,1]<stderr>:2023-04-17 12:18:29.482982: I tensorflow/core/platform/cpu_feature_guard.cc:194] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX
[1,1]<stderr>:To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[1,0]<stderr>:2023-04-17 12:18:29.500944: I tensorflow/core/platform/cpu_feature_guard.cc:194] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX
[1,0]<stderr>:To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[1,0]<stderr>:2023-04-17 12:18:29.646353: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[1,1]<stderr>:2023-04-17 12:18:29.646354: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[1,0]<stdout>:[INFO]: sparse_operation_kit is imported
[1,1]<stdout>:[INFO]: sparse_operation_kit is imported
[1,0]<stderr>:WARNING:tensorflow:Please fix your imports. Module tensorflow.python.training.tracking.base has been moved to tensorflow.python.trackable.base. The old module will be deleted in version 2.11.
[1,1]<stderr>:WARNING:tensorflow:Please fix your imports. Module tensorflow.python.training.tracking.base has been moved to tensorflow.python.trackable.base. The old module will be deleted in version 2.11.
[1,0]<stdout>:[SOK INFO] Import /usr/local/lib/python3.8/dist-packages/merlin_sok-1.1.4-py3.8-linux-x86_64.egg/sparse_operation_kit/lib/libsok_experiment.so
[1,1]<stdout>:[SOK INFO] Import /usr/local/lib/python3.8/dist-packages/merlin_sok-1.1.4-py3.8-linux-x86_64.egg/sparse_operation_kit/lib/libsok_experiment.so
[1,1]<stderr>:2023-04-17 12:18:39.342912: I tensorflow/core/platform/cpu_feature_guard.cc:194] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX
[1,1]<stderr>:To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[1,0]<stderr>:2023-04-17 12:18:39.342944: I tensorflow/core/platform/cpu_feature_guard.cc:194] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX
[1,0]<stderr>:To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[1,1]<stderr>:2023-04-17 12:18:40.277937: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1637] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 30981 MB memory:  -> device: 1, name: Tesla V100-SXM2-32GB, pci bus id: 0000:1b:00.0, compute capability: 7.0
[1,0]<stderr>:2023-04-17 12:18:40.295019: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1637] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 30981 MB memory:  -> device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:1a:00.0, compute capability: 7.0
[1,1]<stdout>:[SOK INFO] Initialize finished, communication tool: horovod
[1,0]<stdout>:[SOK INFO] Initialize finished, communication tool: horovod
[1,1]<stdout>:v1:
[1,1]<stdout>: <tf.Variable 'Variable:0' shape=(8, 3) dtype=float32, numpy=
[1,1]<stdout>:array([[ 3.,  4.,  5.],
[1,1]<stdout>:       [ 9., 10., 11.],
[1,1]<stdout>:       [15., 16., 17.],
[1,1]<stdout>:       [21., 22., 23.],
[1,1]<stdout>:       [27., 28., 29.],
[1,1]<stdout>:       [33., 34., 35.],
[1,1]<stdout>:       [39., 40., 41.],
[1,1]<stdout>:       [45., 46., 47.]], dtype=float32)>
[1,1]<stdout>:v2:
[1,1]<stdout>: <tf.Variable 'Variable:0' shape=(3, 5) dtype=float32, numpy=
[1,1]<stdout>:array([[ 5.,  6.,  7.,  8.,  9.],
[1,1]<stdout>:       [15., 16., 17., 18., 19.],
[1,1]<stdout>:       [25., 26., 27., 28., 29.]], dtype=float32)>
[1,1]<stdout>:indices1:
[1,1]<stdout>: SparseTensor(indices=tf.Tensor(
[1,1]<stdout>:[[0 0]
[1,1]<stdout>: [0 1]
[1,1]<stdout>: [1 0]
[1,1]<stdout>: [1 1]
[1,1]<stdout>: [1 2]], shape=(5, 2), dtype=int64), values=tf.Tensor([1 1 3 4 5], shape=(5,), dtype=int32), dense_shape=tf.Tensor([2 3], shape=(2,), dtype=int64))
[1,1]<stdout>:indices2:
[1,1]<stdout>: SparseTensor(indices=tf.Tensor(
[1,1]<stdout>:[[0 0]
[1,1]<stdout>: [1 0]
[1,1]<stdout>: [1 1]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 2 3], shape=(3,), dtype=int32), dense_shape=tf.Tensor([2 2], shape=(2,), dtype=int64))
[1,0]<stdout>:v1:
[1,0]<stdout>: <tf.Variable 'Variable:0' shape=(9, 3) dtype=float32, numpy=
[1,0]<stdout>:array([[ 0.,  1.,  2.],
[1,0]<stdout>:       [ 6.,  7.,  8.],
[1,0]<stdout>:       [12., 13., 14.],
[1,0]<stdout>:       [18., 19., 20.],
[1,0]<stdout>:       [24., 25., 26.],
[1,0]<stdout>:       [30., 31., 32.],
[1,0]<stdout>:       [36., 37., 38.],
[1,0]<stdout>:       [42., 43., 44.],
[1,0]<stdout>:       [48., 49., 50.]], dtype=float32)>
[1,0]<stdout>:v2:
[1,0]<stdout>: <tf.Variable 'Variable:0' shape=(4, 5) dtype=float32, numpy=
[1,0]<stdout>:array([[ 0.,  1.,  2.,  3.,  4.],
[1,0]<stdout>:       [10., 11., 12., 13., 14.],
[1,0]<stdout>:       [20., 21., 22., 23., 24.],
[1,0]<stdout>:       [30., 31., 32., 33., 34.]], dtype=float32)>
[1,0]<stdout>:indices1:
[1,0]<stdout>: SparseTensor(indices=tf.Tensor(
[1,0]<stdout>:[[0 0]
[1,0]<stdout>: [0 1]
[1,0]<stdout>: [1 0]
[1,0]<stdout>: [1 1]
[1,0]<stdout>: [1 2]], shape=(5, 2), dtype=int64), values=tf.Tensor([1 1 3 4 5], shape=(5,), dtype=int32), dense_shape=tf.Tensor([2 3], shape=(2,), dtype=int64))
[1,0]<stdout>:indices2:
[1,0]<stdout>: SparseTensor(indices=tf.Tensor(
[1,0]<stdout>:[[0 0]
[1,0]<stdout>: [1 0]
[1,0]<stdout>: [1 1]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 2 3], shape=(3,), dtype=int32), dense_shape=tf.Tensor([2 2], shape=(2,), dtype=int64))
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "lookup_sparse_distributed_example.py", line 60, in <module>
[1,0]<stderr>:    embeddings = sok.lookup_sparse([v1, v2], [indices1, indices2], combiners=["sum", "sum"])
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/merlin_sok-1.1.4-py3.8-linux-x86_64.egg/sparse_operation_kit/experiment/lookup.py", line 520, in lookup_sparse
[1,0]<stderr>:    emb_vec_buffer, rsplits = alltoall(emb_vec_buffer, splits)
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/merlin_sok-1.1.4-py3.8-linux-x86_64.egg/sparse_operation_kit/experiment/communication.py", line 217, in alltoall
[1,0]<stderr>:    return _COMM_TOOL.alltoall(*args, **kwargs)
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/merlin_sok-1.1.4-py3.8-linux-x86_64.egg/sparse_operation_kit/experiment/communication.py", line 140, in alltoall
[1,0]<stderr>:    return hvd.alltoall(tensor, splits)
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/horovod/tensorflow/mpi_ops.py", line 429, in alltoall
[1,0]<stderr>:    output, rsplits = MPI_LIB.horovod_alltoall(tensor, splits=splits_, name=name,
[1,0]<stderr>:  File "<string>", line 1759, in horovod_alltoall
[1,0]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 7209, in raise_from_not_ok_status
[1,0]<stderr>:    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
[1,0]<stderr>:tensorflow.python.framework.errors_impl.UnknownError: {{function_node __wrapped__HorovodAlltoall_device_/job:localhost/replica:0/task:0/device:GPU:0}} ncclGroupEnd failed: internal error [Op:HorovodAlltoall]
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "lookup_sparse_distributed_example.py", line 60, in <module>
[1,1]<stderr>:    embeddings = sok.lookup_sparse([v1, v2], [indices1, indices2], combiners=["sum", "sum"])
[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/merlin_sok-1.1.4-py3.8-linux-x86_64.egg/sparse_operation_kit/experiment/lookup.py", line 520, in lookup_sparse
[1,1]<stderr>:    emb_vec_buffer, rsplits = alltoall(emb_vec_buffer, splits)
[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/merlin_sok-1.1.4-py3.8-linux-x86_64.egg/sparse_operation_kit/experiment/communication.py", line 217, in alltoall
[1,1]<stderr>:    return _COMM_TOOL.alltoall(*args, **kwargs)
[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/merlin_sok-1.1.4-py3.8-linux-x86_64.egg/sparse_operation_kit/experiment/communication.py", line 140, in alltoall
[1,1]<stderr>:    return hvd.alltoall(tensor, splits)
[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/horovod/tensorflow/mpi_ops.py", line 429, in alltoall
[1,1]<stderr>:    output, rsplits = MPI_LIB.horovod_alltoall(tensor, splits=splits_, name=name,
[1,1]<stderr>:  File "<string>", line 1759, in horovod_alltoall
[1,1]<stderr>:  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 7209, in raise_from_not_ok_status
[1,1]<stderr>:    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
[1,1]<stderr>:tensorflow.python.framework.errors_impl.UnknownError: {{function_node __wrapped__HorovodAlltoall_device_/job:localhost/replica:0/task:0/device:GPU:0}} ncclGroupEnd failed: internal error [Op:HorovodAlltoall]
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[45210,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by kanghui0204** [comment]
Hi @Nov11 ,this example is the developer use when he first started developing,in that time ,SOK can use embedding vector length in any number , but during develop , we may want to make lookup more fast, every cuda lookup kernel we use vectorized, that need data align with 4*sizeof(float) , so SOK can't support embedding length in any number, only support embedding length is Multiple of 4. 

you can see the solution in this issue:https://github.com/NVIDIA-Merlin/HugeCTR/issues/378 ， and we plan to add a fallback cuda lookup kernel in SOK , and support any number
