### ISSUE TITLE
[Question]When setting use_mixed_precision=True, wdl training does not converge.

### ISSUE THREAD

**Issue by zpcalan** [NVIDIA-Merlin/HugeCTR#393]
Hi, developers of HugeCTR. I create solver by:
```
solver = hugectr.CreateSolver(
    max_eval_batches=300,
    batchsize_eval=16384,
    batchsize=16384,
    lr=0.001,
    vvgpu=[[0]],
    repeat_dataset=False,
    i64_input_key=True,
    use_mixed_precision=True
)
```
And I train wdl with day0 criteo data with ETC.
After several iterations, the exception below is thrown:
```
[HCTR][11:19:55.275][INFO][RK0][main]: Eval Time for 300 iters: 3.4955s
[HCTR][11:20:08.988][INFO][RK0][main]: Iter: 7200 Time(200 iters): 17.1874s Loss: 0.136492 lr:0.001
[HCTR][11:20:22.701][INFO][RK0][main]: Iter: 7400 Time(200 iters): 13.6779s Loss: 0.129374 lr:0.001
[HCTR][11:20:36.423][INFO][RK0][main]: Iter: 7600 Time(200 iters): 13.6861s Loss: 0.131023 lr:0.001
[HCTR][11:20:50.775][INFO][RK0][main]: Iter: 7800 Time(200 iters): 14.3157s Loss: 0.129374 lr:0.001
[HCTR][11:21:05.579][INFO][RK0][main]: Iter: 8000 Time(200 iters): 14.7671s Loss: 0.142044 lr:0.001
[HCTR][11:21:09.291][INFO][RK0][main]: Evaluation, AUC: 0.717902
[HCTR][11:21:09.291][INFO][RK0][main]: Eval Time for 300 iters: 3.70926s
[HCTR][11:21:23.835][INFO][RK0][main]: Iter: 8200 Time(200 iters): 18.216s Loss: 0.131776 lr:0.001
[HCTR][11:21:38.619][INFO][RK0][main]: Iter: 8400 Time(200 iters): 14.7486s Loss: 0.138201 lr:0.001
[HCTR][11:21:55.297][INFO][RK0][main]: Iter: 8600 Time(200 iters): 16.6417s Loss: 0.1373 lr:0.001
Traceback (most recent call last):
  File "train.py", line 265, in <module>
    model.fit(max_iter=2300, display=200, eval_interval=1000, snapshot=1000000, snapshot_prefix="wdl", num_epochs=1)
RuntimeError: Train Runtime error: Loss cannot converge /root/HugeCTR/HugeCTR/src/pybind/model.cpp:2162
```

When setting use_mixed_precision to false, it seems all good.

I check the code and find out that HugeCTR using `m` and `v` of Adam optimizer with half data type when using `use_mixed_precision=True`:
```
struct SparseEmbeddingHashParams;
template <typename TypeEmbeddingComp>
struct OptimizerTensor {
  Tensor2<TypeEmbeddingComp> opt_z_tensors_;  // FTRL z variable.
  Tensor2<TypeEmbeddingComp> opt_n_tensors_;  // FTRL n variable.
  Tensor2<TypeEmbeddingComp>
      opt_m_tensors_; /**< The mi variable storage for adam optimizer in the update_params(). */
  Tensor2<TypeEmbeddingComp>
      opt_v_tensors_; /**< The vi variable storage for adam optimizer in the update_params(). */
  Tensor2<uint64_t> opt_prev_time_tensors_; /**< The previous update time storage for lazy adam
                                                  in update_params(). */
  Tensor2<TypeEmbeddingComp> opt_momentum_tensors_; /**< The momentum variable storage
                                           for the momentum optimizer in the update_params(). */
  Tensor2<TypeEmbeddingComp> opt_accm_tensors_;     /**< The accm variable storage for the
                                                         nesterov optimizer in the update_params(). */
};
```
The size of type `TypeEmbeddingComp` is 2. So I change it to float32 with some other code change.  But still, the result does not converge. 
Can anybody tell me which parameter should I adjust so I can run with correct result when setting `use_mixed_precision=True`?

I can also offer my training script if that helps. Thank you!

**Comment by kanghui0204** [comment]
Hi @zpcalan ,I think we need more infomation：

- Have you try to run without ETC? If you have a try , does it runs well?

- How do you preprocessed the dataset for ETC? how do you generated the keyset for day()?

**Comment by zpcalan** [comment]
> Hi @zpcalan ,I think we need more infomation：
> 
> * Have you try to run without ETC? If you have a try , does it runs well?
> * How do you preprocessed the dataset for ETC? how do you generated the keyset for day()?

I appreciate your quick reply!
1. Yes, I ran without ETC but it still does not converge. The exception is the same.
2. I preprocessed day0~day23 data using `bash preprocess.sh $i /root/HugeCTR/etc_data/day$i nvt 1 0 1` as this [link](https://github.com/NVIDIA-Merlin/HugeCTR/tree/main/samples/wdl#preprocess-the-dataset). As for keyset, I ran this command:
```
cmd_str="python generate_keyset.py  --src_dir_path ./etc_data/day"+str(i)+"/train --keyset_path ./etc_data/day"+str(i)+"/train/_hugectr.keyset"
os.system(cmd_str)
```
As you can see, I generate keyset without slot size array. It should not affect convergence.

**Comment by zpcalan** [comment]
And another information you might be interested in is that I adjust the script `preprocess.sh` so that it can process whole day's dataset instead of only first 5000000 samples. I think it might be a little issue of this script?
```
--- a/tools/preprocess.sh
+++ b/tools/preprocess.sh
@@ -50,10 +50,11 @@ fi

 SCRIPT_TYPE=$3

-echo "Getting the first few examples from the uncompressed dataset..."
+sample_num=`wc -l day_$1|awk '{print $1}'`
+echo "Getting the first few examples from the uncompressed dataset... $sample_num"
 mkdir -p $DST_DATA_DIR/train                         && \
 mkdir -p $DST_DATA_DIR/val                           && \
-head -n 5000000 day_$1 > $DST_DATA_DIR/day_$1_small
+head -n $sample_num day_$1 > $DST_DATA_DIR/day_$1_small
 if [ $? -ne 0 ]; then
        echo "Warning: fallback to find original compressed data day_$1.gz..."
        echo "Decompressing day_$1.gz..."
@@ -62,7 +63,7 @@ if [ $? -ne 0 ]; then
                echo "Error: failed to decompress the file."
                exit 2
        fi
-       head -n 5000000 day_$1 > $DST_DATA_DIR/day_$1_small
+       head -n $sample_num day_$1 > $DST_DATA_DIR/day_$1_small
        if [ $? -ne 0 ]; then
                echo "Error: day_$1 file"
                exit 2
@@ -111,7 +112,7 @@ if [[ $SCRIPT_TYPE == "nvt" ]]; then
                --freq_limit 6                        \
                --device_limit_frac 0.5               \
                --device_pool_frac 0.5                \
-               --out_files_per_proc 8                \
+               --out_files_per_proc 20                \
                --devices "0"                         \
                --num_io_threads 2                    \
         --parquet_format=$IS_PARQUET_FORMAT   \

```

**Comment by kanghui0204** [comment]
Hi @zpcalan ,I guess you include more samples , do you modify the `workspace_size_per_gpu_in_mb`  or` slot_size_array ` value?  those parameters should be increased accordingly

**Comment by zpcalan** [comment]
Yes, I change `workspace_size_per_gpu_in_mb` to 4048 because I set embedding_vec_size to 240. 
But I didn't change `slot_size_array` when I generate keyset files as [this comment](https://github.com/NVIDIA-Merlin/HugeCTR/issues/393#issuecomment-1515589967) says. In my script, I also didn't change `slot_size_array ` so it's all 0s.

**Comment by JacoCheung** [comment]
Hi @zpcalan , I assumed that you were using `Parquet` Dataset, right? How is your slot_size_array like in `DataReaderParams`? Let's focus on the model without ETC feature first. 

Do you mind  posting your script here?

**Comment by JacoCheung** [comment]
BTW, @zpcalan  have you ever tried without mixed precision training?

**Comment by JacoCheung** [comment]
No, I think if you're using our preprocessing script, there is no guarantee that keys range of 2 slots are unique. For instance, 
`C0` and `C1` have the chance to be identical **[12, 12... ]**.

**Comment by zpcalan** [comment]
> No, I think if you're using our preprocessing script, there is no guarantee that keys range of 2 slots are unique. For instance, `C0` and `C1` have the chance to be identical **[12, 12... ]**.

Do you mean `C0` and `C1` of one sample could be both 12?
If so, I understand the offset must be added so that keys of each slot in a sample are unique. But why is this happening.

I will set `slot_size_array` and run FP16 training.
It is printed when preprocessing dataset, right? Just like this:
```
Preprocessing
Train Datasets Preprocessing.....
[932326, 1066648, 831979, 24672, 14847, 7123, 19357, 4, 6469, 1268, 55, 696499, 171522, 121926, 11, 2200, 8868, 64, 4, 951, 15, 838640, 446266, 793237, 130145, 10112, 83, 34]
Valid Datasets Preprocessing.....
[932326, 1066648, 831979, 24672, 14847, 7123, 19357, 4, 6469, 1268, 55, 696499, 171522, 121926, 11, 2200, 8868, 64, 4, 951, 15, 838640, 446266, 793237, 130145, 10112, 83, 34]
```

So I will set `slot_size_array`  to `[932326, 1066648, 831979, 24672, 14847, 7123, 19357, 4, 6469, 1268, 55, 696499, 171522, 121926, 11, 2200, 8868, 64, 4, 951, 15, 838640, 446266, 793237, 130145, 10112, 83, 34]`.

**Comment by JacoCheung** [comment]
>  But why is this happening.
The uniqueness requirement derives from the Embedding, you can assume that for `Norm` or `Raw`, the keys are already guaranteed to be unique in the preprocessing. But for `Parquet`, it's the data reader's duty to add a offset to make them unique. The data preprocessing of `Parquet` is done per feature. Different slots would not interfere with each other. For example, `C0` may indicate the `user_id` while `C1` may indicate the `item_id`, nvt will process them individually so that `C0` and `C1` all start with `0`.  Sorry for the inconsistency, we're trying to improve the user experience. 
You can try [embedding collection](https://nvidia-merlin.github.io/HugeCTR/v23.04.00/notebooks/embedding_collection.html), which is a uniform and new embedding type.

> It is printed when preprocessing dataset, right?
Yes.

**Comment by zpcalan** [comment]
Thanks for explaining!

After offset is added to each key, total unique key number will be summation of `[932326, 1066648, 831979, 24672, 14847, 7123, 19357, 4, 6469, 1268, 55, 696499, 171522, 121926, 11, 2200, 8868, 64, 4, 951, 15, 838640, 446266, 793237, 130145, 10112, 83, 34]`，right?  

If so, single card's memory size will not be enough for embedding. ETC must be introduced.
My original goal is to run day0-23 ETC training with FP16.
I can run FP16 training with small dataset and if it converges, can I use ETC training to run day0's dataset?

**Comment by zpcalan** [comment]
Hi, developers of HugeCTR.
I tried to run FP16 training with small dataset and parquet data format, and slot_size_array correctly assigned. but after several steps the auc continued to decline and finally it does not converge.
The script is:
```
import hugectr
from mpi4py import MPI

solver = hugectr.CreateSolver(
    max_eval_batches=300,
    batchsize_eval=16384,
    batchsize=16384,
    lr=0.001,
    vvgpu=[[0]],
    repeat_dataset=False,
    i64_input_key=True,
    use_mixed_precision=True
)

reader = hugectr.DataReaderParams(
    data_reader_type=hugectr.DataReaderType_t.Parquet,
    source=["./etc_data/small_day0/train/_file_list.txt"],
    keyset = ["./etc_data/small_day0/train/_hugectr.keyset"],
    eval_source="./etc_data/small_day0/val/_file_list.txt",
    slot_size_array=[13332, 31854, 10950, 6598, 8743, 4261, 10704, 4, 5009, 991, 28, 12198, 8710, 13823, 10, 1426, 3437, 48, 4, 643, 15, 10765, 11862, 11316, 8432, 5954, 42, 33],
    check_type=hugectr.Check_t.Non,
)

optimizer = hugectr.CreateOptimizer(
    optimizer_type=hugectr.Optimizer_t.Adam,
    update_type=hugectr.Update_t.Global,
    beta1=0.9,
    beta2=0.999,
    epsilon=0.0000001,
)

model = hugectr.Model(solver, reader, optimizer)
model.add(
    hugectr.Input(
        label_dim=1,
        label_name="label",
        dense_dim=13,
        dense_name="dense",
        data_reader_sparse_param_array=[
            hugectr.DataReaderSparseParam("wide_data", 30, True, 1),
            hugectr.DataReaderSparseParam("deep_data", 2, False, 26),
        ],
    )
)
model.add(
    hugectr.SparseEmbedding(
        embedding_type=hugectr.Embedding_t.DistributedSlotSparseEmbeddingHash,
        workspace_size_per_gpu_in_mb=69,
        embedding_vec_size=1,
        combiner="sum",
        sparse_embedding_name="sparse_embedding2",
        bottom_name="wide_data",
        optimizer=optimizer,
    )
)
model.add(
    hugectr.SparseEmbedding(
        embedding_type=hugectr.Embedding_t.LocalizedSlotSparseEmbeddingHash,
        workspace_size_per_gpu_in_mb=1024,
        embedding_vec_size=240,
        combiner="sum",
        sparse_embedding_name="sparse_embedding1",
        bottom_name="deep_data",
        optimizer=optimizer,
    )
)
model.add(
    hugectr.DenseLayer(
        layer_type=hugectr.Layer_t.Reshape,
        bottom_names=["sparse_embedding1"],
        top_names=["reshape1"],
        leading_dim=6240,
    )
)
model.add(
    hugectr.DenseLayer(
        layer_type=hugectr.Layer_t.Reshape,
        bottom_names=["sparse_embedding2"],
        top_names=["reshape2"],
        leading_dim=1,
    )
)
model.add(
    hugectr.DenseLayer(
        layer_type=hugectr.Layer_t.Concat, bottom_names=["reshape1", "dense"], top_names=["concat1"]
    )
)
model.add(
    hugectr.DenseLayer(
        layer_type=hugectr.Layer_t.InnerProduct,
        bottom_names=["concat1"],
        top_names=["fc1"],
        num_output=1024,
    )
)
model.add(
    hugectr.DenseLayer(layer_type=hugectr.Layer_t.ReLU, bottom_names=["fc1"], top_names=["relu1"])
)
model.add(
    hugectr.DenseLayer(
        layer_type=hugectr.Layer_t.Dropout,
        bottom_names=["relu1"],
        top_names=["dropout1"],
        dropout_rate=0.5,
    )
)
model.add(
    hugectr.DenseLayer(
        layer_type=hugectr.Layer_t.InnerProduct,
        bottom_names=["dropout1"],
        top_names=["fc2"],
        num_output=1024,
    )
)
model.add(
    hugectr.DenseLayer(layer_type=hugectr.Layer_t.ReLU, bottom_names=["fc2"], top_names=["relu2"])
)
model.add(
    hugectr.DenseLayer(
        layer_type=hugectr.Layer_t.Dropout,
        bottom_names=["relu2"],
        top_names=["dropout2"],
        dropout_rate=0.5,
    )
)
model.add(
    hugectr.DenseLayer(
        layer_type=hugectr.Layer_t.InnerProduct,
        bottom_names=["dropout2"],
        top_names=["fc3"],
        num_output=1024,
    )
)
model.add(
    hugectr.DenseLayer(layer_type=hugectr.Layer_t.ReLU, bottom_names=["fc3"], top_names=["relu3"])
)
model.add(
    hugectr.DenseLayer(
        layer_type=hugectr.Layer_t.Dropout,
        bottom_names=["relu3"],
        top_names=["dropout3"],
        dropout_rate=0.5,
    )
)
model.add(
    hugectr.DenseLayer(
        layer_type=hugectr.Layer_t.InnerProduct,
        bottom_names=["dropout3"],
        top_names=["fc4"],
        num_output=1024,
    )
)
model.add(
    hugectr.DenseLayer(layer_type=hugectr.Layer_t.ReLU, bottom_names=["fc4"], top_names=["relu4"])
)
model.add(
    hugectr.DenseLayer(
        layer_type=hugectr.Layer_t.Dropout,
        bottom_names=["relu4"],
        top_names=["dropout4"],
        dropout_rate=0.5,
    )
)
model.add(
    hugectr.DenseLayer(
        layer_type=hugectr.Layer_t.InnerProduct,
        bottom_names=["dropout4"],
        top_names=["fc5"],
        num_output=1024,
    )
)
model.add(
    hugectr.DenseLayer(layer_type=hugectr.Layer_t.ReLU, bottom_names=["fc5"], top_names=["relu5"])
)
model.add(
    hugectr.DenseLayer(
        layer_type=hugectr.Layer_t.Dropout,
        bottom_names=["relu5"],
        top_names=["dropout5"],
        dropout_rate=0.5,
    )
)
model.add(
    hugectr.DenseLayer(
        layer_type=hugectr.Layer_t.InnerProduct,
        bottom_names=["dropout5"],
        top_names=["fc6"],
        num_output=1024,
    )
)
model.add(
    hugectr.DenseLayer(layer_type=hugectr.Layer_t.ReLU, bottom_names=["fc6"], top_names=["relu6"])
)
model.add(
    hugectr.DenseLayer(
        layer_type=hugectr.Layer_t.Dropout,
        bottom_names=["relu6"],
        top_names=["dropout6"],
        dropout_rate=0.5,
    )
)
model.add(
    hugectr.DenseLayer(
        layer_type=hugectr.Layer_t.InnerProduct,
        bottom_names=["dropout6"],
        top_names=["fc7"],
        num_output=1024,
    )
)
model.add(
    hugectr.DenseLayer(layer_type=hugectr.Layer_t.ReLU, bottom_names=["fc7"], top_names=["relu7"])
)
model.add(
    hugectr.DenseLayer(
        layer_type=hugectr.Layer_t.Dropout,
        bottom_names=["relu7"],
        top_names=["dropout7"],
        dropout_rate=0.5,
    )
)
model.add(
    hugectr.DenseLayer(
        layer_type=hugectr.Layer_t.InnerProduct,
        bottom_names=["dropout7"],
        top_names=["fc8"],
        num_output=1,
    )
)
model.add(
    hugectr.DenseLayer(
        layer_type=hugectr.Layer_t.Add, bottom_names=["fc8", "reshape2"], top_names=["add1"]
    )
)
model.add(
    hugectr.DenseLayer(
        layer_type=hugectr.Layer_t.BinaryCrossEntropyLoss,
        bottom_names=["add1", "label"],
        top_names=["loss"],
    )
)
model.compile()
model.summary()
model.fit(max_iter=1, display=10, eval_interval=40, snapshot=1000000, snapshot_prefix="wdl", num_epochs=100)
```

The result:
```
[HCTR][12:21:15.423][INFO][RK0][main]: Eval Time for 300 iters: 0.66509s
[HCTR][12:21:15.900][INFO][RK0][main]: Iter: 4170 Time(10 iters): 1.13876s Loss: 0.0917276 lr:0.001
[HCTR][12:21:16.438][INFO][RK0][main]: Iter: 4180 Time(10 iters): 0.533409s Loss: 0.0895059 lr:0.001
[HCTR][12:21:16.939][INFO][RK0][main]: Iter: 4190 Time(10 iters): 0.495925s Loss: 0.086796 lr:0.001
[HCTR][12:21:17.395][INFO][RK0][main]: Iter: 4200 Time(10 iters): 0.451196s Loss: 0.0831752 lr:0.001
[HCTR][12:21:18.081][INFO][RK0][main]: Evaluation, AUC: 0.602723
[HCTR][12:21:18.081][INFO][RK0][main]: Eval Time for 300 iters: 0.684147s
[HCTR][12:21:18.552][INFO][RK0][main]: Iter: 4210 Time(10 iters): 1.15236s Loss: 0.0809434 lr:0.001
[HCTR][12:21:18.684][INFO][RK0][main]: train drop incomplete batch. batchsize:10752
[HCTR][12:21:18.684][INFO][RK0][main]: -----------------------------------Epoch 43-----------------------------------
[HCTR][12:21:19.083][INFO][RK0][main]: Iter: 4220 Time(10 iters): 0.526233s Loss: 0.077393 lr:0.001
[HCTR][12:21:19.552][INFO][RK0][main]: Iter: 4230 Time(10 iters): 0.464746s Loss: 0.078123 lr:0.001
[HCTR][12:21:20.005][INFO][RK0][main]: Iter: 4240 Time(10 iters): 0.447292s Loss: 0.0808783 lr:0.001
[HCTR][12:21:20.694][INFO][RK0][main]: Evaluation, AUC: 0.611602
[HCTR][12:21:20.694][INFO][RK0][main]: Eval Time for 300 iters: 0.688137s
Traceback (most recent call last):
  File "small_wdl.py", line 267, in <module>
    model.fit(max_iter=1, display=10, eval_interval=40, snapshot=1000000, snapshot_prefix="wdl", num_epochs=1000)
RuntimeError: Train Runtime error: Loss cannot converge /hugectr/HugeCTR/src/pybind/model.cpp:2019
```
Is there something wrong with the script?

**Comment by zpcalan** [comment]
Hi, any progress on this issue? It seems some convergence issue when using `use_mixed_precision=True`.

**Comment by JacoCheung** [comment]
It looks like you were using `epoch` mode and the dataset contained `68976640 (16384*4210)` samples or so, right? 
Could you please post the AUC for each epoch? I'd like to know when the AUC did start to drop. 

In addition, we had not tried enabling fp16 training for this model, the hyper parameters may be subtly different from of fp32 training. For example, the ,`scaler`, `learning_rate`,  etc.  Please refer to [solver document](https://nvidia-merlin.github.io/HugeCTR/main/api/python_interface.html#solver) for more details.

**Comment by JacoCheung** [comment]
Becuse HugeCTR does not support dynamic scaler, the divergence issue sometimes occurs if there's `fp16` overflow (For example, the weight is too large and the gemm will produce intermediate numeric larger than 65,504(Inf) and the inf will propagate).

**Comment by JacoCheung** [comment]
Yes, the hyper params (in the worst case, you had to opt another optimizer) should be adjusted. We have not fully tested fp16 training for all models.

There are two remarks from the AUC log you posted:
1. The AUC in the first epoch is much smaller than that with `fp32`. It may imply that this model+current configuration are not suitale for `fp16` training.
2.The AUC tends to drop after many epochs. It may imply overfitting.

Anyway, I recommend you to adjust some hyper parameters.

**Comment by zpcalan** [comment]
Thanks. I will adjust as you suggest.
By the way, could you please check [this issue about ETC](https://github.com/NVIDIA-Merlin/HugeCTR/issues/397)? I am trying to run this test regardless disconvergence. 
I appreciate it a lot!

**Comment by zpcalan** [comment]
I am trying not to use `use_mixed_precision` parameter and manully add `hugectr.Layer_t.Cast` layer instead to fix this convergence issue while keep the performance consistent. But the API document seems lack of `hugectr.Layer_t.Cast` layer's description. How can I use this type of DenseLayer to cast output to float16, for example.

**Comment by zpcalan** [comment]
I use dlrm instead of W&D because the parameters in the script have been already configured correctly for mixed precision.
Issue closed. : )
