### ISSUE TITLE
Can't install sparse_operation_kit

### ISSUE THREAD

**Issue by yourtj** [NVIDIA-Merlin/HugeCTR#396]
when I run "pip install sparse_operation_kit" to install sparse_operation_kit, I got following error. I tried both in MacOs and Ubuntu18. Could someone help me figure out the issue? Thanks! 

```Building wheel for merlin-sok (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/jie_tang/miniconda3/bin/python /Users/jie_tang/miniconda3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/63/kknj2pms1q9_dpcpyzd0nfkw0000gn/T/tmpotdvjpgq
       cwd: /private/var/folders/63/kknj2pms1q9_dpcpyzd0nfkw0000gn/T/pip-install-rkxqpns9/merlin-sok
  Complete output (12 lines):
  cp: ../HugeCTR: No such file or directory
  mkdir: third_party: File exists
  cp: ../third_party/json: No such file or directory
  Traceback (most recent call last):
    File "/private/var/folders/63/kknj2pms1q9_dpcpyzd0nfkw0000gn/T/pip-build-env-3yfqbb9b/overlay/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
      cmkr = cmaker.CMaker(cmake_executable)
    File "/private/var/folders/63/kknj2pms1q9_dpcpyzd0nfkw0000gn/T/pip-build-env-3yfqbb9b/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 148, in __init__
      self.cmake_version = get_cmake_version(self.cmake_executable)
    File "/private/var/folders/63/kknj2pms1q9_dpcpyzd0nfkw0000gn/T/pip-build-env-3yfqbb9b/overlay/lib/python3.8/site-packages/skbuild/cmaker.py", line 105, in get_cmake_version
      raise SKBuildError(msg) from err
  
  Problem with the CMake installation, aborting build. CMake executable is cmake
  ----------------------------------------
  ERROR: Failed building wheel for merlin-sok
Successfully built sparse-operation-kit
Failed to build merlin-sok
ERROR: Could not build wheels for merlin-sok which use PEP 517 and cannot be installed directly```

**Comment by kanghui0204** [comment]
Hi , please check your software version meet this requirement : https://github.com/NVIDIA-Merlin/HugeCTR/tree/main/sparse_operation_kit#pre-requisites
please use below step install :
1.git clone https://github.com/NVIDIA-Merlin/HugeCTR.git
2.cd HugeCTR/sparse_operation_kit 
3.mkdir build && cmake -DSM={your cuda SM level ,for example 80 70 } ../  
4.make -j && make install
5.cp -r ../sparse_operation_kit /usr/local/lib/python3.8/dist-packages/
then you can use sok in python.

**Comment by RayWang96** [comment]
Hi, [yourtj](https://github.com/yourtj). Is this problem solved?
